user = "papertigers"
token = "foobarbazfoobarbazfoobarbazfoobarbaz"

organizations = [
    "illumos",
    "omniosorg",
]

users = [
    "papertigers",
]

[owner.bahamas10]
repos = [
    "rust-zonename",
]

[owner.oxidecomputer]
repos = [
    "propolis",
]
